### ISSUE TITLE
Automating time axis for graph

### ISSUE THREAD

**Issue by HeleneDyrmose** [Ekimu/InvestmentGameGroup2#7]

**Comment by lisadaehne** [comment]
Also add the name of the stock to the graph

**Comment by HeleneDyrmose** [comment]
Pandas contains lots of functions for working with time series. This is important for this project.

See the pandas documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html

See also documentation about datetime properties for series: https://pandas.pydata.org/pandas-docs/stable/reference/series.html#datetimelike-properties

And a nice little tutorial about resampling: http://benalexkeen.com/resampling-time-series-data-with-pandas/
